# Generated by Django 3.2.4 on 2021-06-30 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('complement', models.CharField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=45)),
                ('zip_code', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Zip Code must be 00000000 or 00000-000 format.', regex='^[0-9]{5}-?[0-9]{3}$')])),
                ('tag', models.CharField(max_length=45)),
            ],
        ),
    ]
