# Generated by Django 3.2.4 on 2021-07-01 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='secondaries_addressess',
            new_name='secondaries_addresses',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid brazilian phone number.', regex='^[1-9]{2}9[1-9][0-9]{7}$')]),
        ),
    ]
