# Generated by Django 3.2.4 on 2021-07-02 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='secondaries_addresses',
            new_name='secondary_addresses',
        ),
    ]
